"""update post table

Revision ID: b8f77fb045f7
Revises: 4d472b8e24b5
Create Date: 2023-08-04 10:35:25.960145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f77fb045f7'
down_revision = '4d472b8e24b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=True),
    sa.Column('access_expiration', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(length=64), nullable=True),
    sa.Column('refresh_expiration', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_access_token'), ['access_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_refresh_token'), ['refresh_token'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_token')
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('token_expiration', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_user_token', ['token'], unique=False)

    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_refresh_token'))
        batch_op.drop_index(batch_op.f('ix_token_access_token'))

    op.drop_table('token')
    # ### end Alembic commands ###
